### PR TITLE
Use service binding for all Mouse and KeyListeners

### PR DESCRIPTION
**Pull request by dhuebner**
Make it simpler to extend existing mouse and key listeners.

### CODE REVIEW

**Comment by tortmayr** [comment]
Great change! This definitely makes it easier to customize existing listeners

 > Still need to review which Listeners can be bound in singleton scope

IMO all mouse listeners can  be bound in singleton scope without side effects.
Currently they are only constructor injected into the `MouseTool`. The MouseTool is bound in Singleton scope which effectively makes the injected listeners singleton as well.

**Comment by dhuebner** [comment]
@tortmayr 
> IMO all mouse listeners can be bound in singleton scope without side effects. 

Now all MouseListeners are singletons. I hope I didn't overlooked one...

**Comment by spoenemann** [comment]
@dhuebner would you mind doing the same for KeyListeners?

**Comment by dhuebner** [comment]
@spoenemann 
In the same PR? 
Sure, also all as singleton binding?

**Comment by tortmayr** [comment]
> Now all MouseListeners are singletons. I hope I didn't overlooked one...

@dhuebner Looks good to me. I guess we should also do the same for `PopupMouseListeners`?.

**Comment by spoenemann** [comment]
@dhuebner yes, KeyListeners and PopupMouseListeners behave with the same concept as MouseListeners. It would be great to have a consistent DI approach with all of these.

**Comment by dhuebner** [comment]
@tortmayr @spoenemann 
I think, I have all of them migrated now

**Review by spoenemann — APPROVED** [review]

**Pull request merged**
