### PR TITLE
Copied sprotty-elk package into this repository

### PR DESCRIPTION
**Pull request by spoenemann**
As discussed in #243, I copied the `sprotty-elk` package into the main repository. I also removed the dependency to `sprotty` and added a dependency to `sprotty-protocol` instead. This enables to use `sprotty-elk` in a Node.js backend. The downside of this change is that we can no longer include the binding to `TYPES.IModelLayoutEngine` in the `elkLayoutModule`, but I think that's ok. I documented this breaking change in the CHANGELOG.md of that package.

### CODE REVIEW

**Comment by spoenemann** [comment]
After this is merged, we can archive https://github.com/eclipse/sprotty-layout and I'll publish version 0.11.0.

**Comment by spoenemann** [comment]
@tohosaku you're welcome to review as well. For some reason I can't select you as reviewer, although you are listed as committer (https://projects.eclipse.org/projects/ecd.sprotty/who).

I hope this is the last big restructuring PR. After that I'll stop spamming y'all :-)

**Review by planger — APPROVED** [review]
Thanks, looks good to me! :+1:

**Comment by tortmayr** [comment]
> @tohosaku you're welcome to review as well. For some reason I can't select you as reviewer, although you are listed as committer (https://projects.eclipse.org/projects/ecd.sprotty/who).

We also had this issue previously. I think you have to update the account settings of your Eclipse.org account. You need to set your github username so that the Eclipse IT can sync your account and configure the corresponding permissions for  the sprotty repos.
@tohosaku  Please check your Eclipse.org profile settings and make sure that you have set your github handle in the `Social Media Links` section
Screenshot from 2021-11-19 10-26-07

**Comment by spoenemann** [comment]
I realized there was a missing dependency to `inversify`. In order to make that optional, I removed the DI module from `index.ts` because I don't want to force the dependency to Inversify on NodeJS backends for Sprotty. I documented this in CHANGELOG.md.

I also added another example showing automatic layout with `elkjs` in the browser, and removed the "mindmap" example (I started that years ago with a specific idea in mind, but never found the time / motivation to finish it).

@planger @tortmayr are you ok with these additional changes?

**Review by planger — APPROVED** [review]
Yes, looks good to me! Thanks!

**Pull request merged**
