### PR TITLE
MouseEvents: corrected doubleClick to be a MouseEvent

### PR DESCRIPTION
**Pull request by manfred4**
Completes Issue #57

### CODE REVIEW

**Comment by JanKoehnlein** [comment]
Sorry, Eclipse forces commits by non-committers to be signed-off.
Could you amend the commit, sign it off and force push it?

**Comment by JanKoehnlein** [comment]
Filed a feature request to Gitpod. https://github.com/gitpod-io/gitpod/issues/308

**Comment by spoenemann** [comment]
The [Eclipse ECA](https://www.eclipse.org/legal/ECA.php) is also missing. I created #64 for documenting all this.

**Comment by NiklasRentzCAU** [comment]
I just created another pull request with my new, non-private account which as signed the Eclipse ECA and has signed off commits.
This pull request can be deleted or you can keep and archive it for documentation puropses of the ECA and signed-off issues.

**Comment by JanKoehnlein** [comment]
See https://github.com/eclipse/sprotty/pull/66

**Pull request closed without merging**
